# Generated by Django 4.2.7 on 2026-09-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_btc_balance_user_transaction_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', 'Signup verification'), ('withdrawal', 'Withdrawal authorisation')], default='signup', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('country_of_citizenship', models.CharField(blank=True, max_length=100)),
                ('citizenship_status', models.CharField(blank=True, max_length=100)),
                ('tax_id_type', models.CharField(blank=True, choices=[('ssn', 'SSN'), ('itin', 'ITIN'), ('ein', 'EIN'), ('other', 'Other')], max_length=10)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], max_length=20)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('years_employed', models.CharField(blank=True, max_length=20)),
                ('employer_phone', models.CharField(blank=True, max_length=30)),
                ('annual_income', models.CharField(blank=True, max_length=50)),
                ('source_of_income', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('drivers_license', "Driver's licence"), ('national_id', 'National ID'), ('state_id', 'State ID')], max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=60)),
                ('id_state', models.CharField(blank=True, max_length=100)),
                ('id_issue_date', models.DateField(blank=True, null=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('security_question', models.CharField(blank=True, max_length=200)),
                ('security_answer', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('incomplete', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=12)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_em_user_id_7388a1_idx'),
        ),
    ]
