# Generated by Django 4.2.7 on 2026-09-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp_kycprofile_delete_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfers_blocked',
            field=models.BooleanField(default=False, help_text='Block this customer from sending money. They keep full read access and are told to contact support.'),
        ),
    ]
