# Generated by Django 4.2.7 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_transfers_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='btc_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='btc_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_on_expiration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_on_roi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eth_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ltc_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usdt_address',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('referral', 'Referral'), ('system', 'System'), ('security', 'Security')], default='system', max_length=20),
        ),
    ]
