# Generated by Django 4.2.7 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('account', 'Account Issue'), ('deposit', 'Deposit Issue'), ('withdrawal', 'Withdrawal Issue'), ('technical', 'Technical Issue'), ('general', 'General Inquiry'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
