# Generated by Django 4.2.7 on 2026-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_beneficiary_paymentmethod_swaprate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_enabled', models.BooleanField(default=False, help_text='Show currency swap in the app. Off by default.')),
                ('loans_enabled', models.BooleanField(default=True, help_text='Show loan applications.')),
                ('grants_enabled', models.BooleanField(default=True, help_text='Show grant applications.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flags',
                'verbose_name_plural': 'Feature Flags',
            },
        ),
    ]
