# Generated by Django 4.2.7 on 2026-09-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_featureflags'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='funds_held',
            field=models.BooleanField(default=False, help_text='Money already debited when the request was submitted, so approving must not debit again.'),
        ),
    ]
