# Generated by Django 4.2.7 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_funds_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='user',
        ),
        migrations.DeleteModel(
            name='SwapRate',
        ),
        migrations.RemoveField(
            model_name='featureflags',
            name='swap_enabled',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='wallet_address',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Method-specific details (email, tag, etc.)'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='type',
            field=models.CharField(choices=[('local_bank', 'Local Bank'), ('wire', 'International Wire'), ('paypal', 'PayPal'), ('wise', 'Wise'), ('cashapp', 'Cash App'), ('other', 'Other')], default='local_bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='method',
            field=models.CharField(choices=[('local_bank', 'Local Bank'), ('wire', 'Wire Transfer'), ('paypal', 'PayPal'), ('wise', 'Wise'), ('cashapp', 'Cash App'), ('other', 'Other')], default='local_bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(help_text='e.g., Bank Transfer', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_address',
            field=models.CharField(blank=True, help_text='Bank account details', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Credit/Debit Card')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('bonus', 'Bonus'), ('referral', 'Referral Bonus'), ('loan', 'Loan Disbursement'), ('grant', 'Grant Disbursement')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Swap',
        ),
    ]
